# Generated by Django 4.2.9 on 2024-01-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bookreview", name="content",),
        migrations.AlterField(
            model_name="bookreview",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="bookreview", name="rating", field=models.IntegerField(),
        ),
    ]
